name: control_eventos_qr
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  qr_code_scanner: ^0.0.12
  cloud_firestore: ^0.12.9+4
  shared_preferences: ^0.5.3+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/asistant.png
    - assets/images/cloud.png
    - assets/images/comtec.png
    - assets/images/firebase.png
    - assets/images/gdg.png
    - assets/images/jala.png
    - assets/images/marketing.png
    - assets/images/mobile.png
    - assets/images/piu.png
    - assets/images/tensorflow.png
    - assets/images/ucb.png
    - assets/images/web.png
  
  fonts:
    - family: Custom Icons
      fonts:
        - asset: assets/icons/custom_icons.ttf